[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "python-tmx"
version = "0.1.5-dev"
authors = [
  { name="Enzo Agosta", email="agosta.enzowork@gmail.com" },
]
description = "Python library for manipulating, creating and editing tmx files"
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "MIT" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["lxml>=5.1.0", "python-dateutil>=2.9.0"]

[project.optional-dependencies]
dev = ["black", "lxml-stubs>=0.5.1", "ruff", "pytest", "mypy", "requests", "wheel"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.mypy]
mypy_path = "src"
warn_unused_configs = true
allow_redefinition = false
explicit_package_bases = true
ignore_missing_imports = false
implicit_reexport = false
no_implicit_optional = true

[project.urls]
Homepage = "https://github.com/ChonkyYoshi/python-tmx"
Issues = "https://github.com/ChonkyYoshi/python-tmx/issues"